server:
  port: 8085
spring:
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:mem:/pamcary
    platform: h2
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
